name: "CI"

on:
  push:
  pull_request:
    # We don't run on PR synchronize, because that would duplicate the push-Build
    types:
      - opened

jobs:
  ci:
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    # https://github.com/questionpy-org/.github
    uses: questionpy-org/.github/.github/workflows/python-ci.yml@feature/ci-version-matrix
    with:
      packages: questionpy_common
      python-version: ${{ matrix.python-version }}
